### PR TITLE
Add spaces:wait

### PR DESCRIPTION
**Pull request by archaelus**
Adds a command (written by someone who doesn't know javascript) to block waiting for space creation to complete. Pretty much like `pg:wait`, but for space creation.

### CODE REVIEW

**Comment by sclasen** [comment]
👍 👍 👍

**Comment by dpiddy** [comment]
Can this be revived?

Any way to share space display and such with spaces:info?

**Comment by archaelus** [comment]
I am not a good javascripter. Someone else should take this over :3

**Comment by ryanbrainard** [comment]
I can try to take a look today

**Comment by ryanbrainard** [comment]
Still needs tests, but i cleaned thing up a bit

**Comment by ryanbrainard** [comment]
Added a test.

**Comment by ryanbrainard** [comment]
One thing we should consider doing is adding a `--wait` flag to `spaces:create` to automatically invoke `spaces:wait`. Thoughts?

**Comment by dpiddy** [comment]
👍

I'd say not yet on `spaces:create --wait`.

**Comment by ryanbrainard** [comment]
Ok, pulling this in as-is. We can do `spaces:create --wait` later if we want.

**Pull request merged**
